name: Train Chatbot Model

env:
  MY_SECRET_PASSWORD: ${{ secrets.DB_PASSWORD }}

on:
  push:
    branches: [ main ]
    paths:
      - 'qa_pairs.json'
      - 'bot_trainer.py'
      - 'use_chatbot.py'
      - 'web_app.py'
      - 'docs/**'
  
  # Manual trigger
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scikit-learn fastapi uvicorn
        
    - name: Train chatbot model
      run: python bot_trainer.py
      
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: chatbot-model
        path: chatbot_model.pkl
        
    - name: Notify on fork or push
      if: github.event_name == 'fork' || (github.event_name == 'push' && github.actor != 'BishalBabuDumre')
      uses: actions/github-script@v6
      with:
        script: |
          const bodyLines = [
            `Activity type: ${context.eventName}`,
            `Triggered by: @${context.actor}`,
            `Branch: ${context.ref}`,
            context.payload.head_commit ? `Commit message: ${context.payload.head_commit.message}` : '',
            context.payload.head_commit ? `Commit SHA: ${context.sha}` : '',
            `View details: ${context.payload.repository.html_url}/actions/runs/${context.runId}`
          ].filter(Boolean).join('\n\n');

          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Repository activity by ${context.actor}`,
            body: bodyLines,
            labels: ['notification']
          })


  deploy:
    needs: train
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}  # <-- Personal Access Token (PAT) with `packages:write` & `packages:delete`
        fetch-depth: 0
  
    - name: Download model artifact
      uses: actions/download-artifact@v4
      with:
        name: chatbot-model
        path: ./
        
    - name: Commit and push trained model
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add chatbot_model.pkl
        git commit -m "Update chatbot model [skip ci]" || echo "No changes to commit"
        git push origin HEAD

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}   # <-- same PAT with package permissions

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/chatbot:latest
        docker build -t $IMAGE_NAME .
    
    - name: Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/chatbot:latest
        docker push $IMAGE_NAME
